config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins
  root to: 'home#index'
  namespace :user do
    root to: 'home#index'
  end
  namespace :admin do
    root to: 'home#index'
  end
  resources :shipping_companies, only: %i[index new create show] do
    member do
      patch 'deactivate'
      patch 'activate'
    end
  end
  resources :shipping_prices, only: %i[index new create]
  resources :min_shipping_prices, only: %i[new create]
  resources :shipping_deadlines, only: %i[index new create]
  resources :items, only: %i[new create]
  resources :quotes, only: %i[index] do
    get 'generated', on: :collection
  end
  resources :service_orders, only: %i[new create show index] do
    member do
      get 'set_vehicle'
      patch 'accept'
      patch 'reject'
    end
    resources :route_updates, only: %i[index create]
    get 'tracking', on: :collection
  end
  resources :vehicles, only: %i[index new create]
end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :item
  belongs_to :shipping_company

  validates :price, :deadline, presence: true
  validates :deadline, numericality: { only_integer: true }

  before_create :generate_code

  private

  def generate_code
    self.code = SecureRandom.alphanumeric(12).upcase
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :authenticate_admin!

  def generated
    distance = params[:d]
    @item = Item.find(params[:i])
    @quotes = QuoteCreator.call(@item, distance)
  end

  def index
    @quotes = Quote.order(created_at: :desc)
  end
end

app/views/quotes/_quotes.html.erb
<table>
  <thead>
    <tr>
      <th>Data</th>
      <th>Código</th>
      <th>Item</th>
      <th>Transportadora</th>
      <th>Preço</th>
      <th>Prazo</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @quotes.each do |quote| %>
    <tr>
      <td><%= l(quote.created_at.to_date) %></td>
      <td><%= quote.code %></td>
      <td><%= quote.item.sku %></td>
      <td><%= quote.shipping_company.brand_name %></td>
      <td><%= number_to_currency(quote.price) %></td>
      <td><%= quote.deadline %> dias úteis</td>
      <td><%= link_to 'Criar Ordem de Serviço', new_service_order_path(q: quote.code) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/quotes/generated.html.erb
<h2>Cotações para <%= @item.sku %></h2>
<% if @quotes.any? %>
  <p><%= @quotes.count %> <%= ShippingCompany.model_name.human(count: @quotes.count).downcase %> <%= t(:found, count: @quotes.count) %></p>
  <%= render 'quotes' %>
<% else %>
  <p>Nenhuma transportadora atende esses requisitos</p>
<% end %>

app/views/quotes/index.html.erb
<h2>Cotações</h2>
<% if @quotes.any? %>
  <%= render 'quotes' %>
<% else %>
  <p>Ainda não foram geradas cotações</p>
<% end %>