config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins
  root to: 'home#index'
  namespace :user do
    root to: 'home#index'
  end
  namespace :admin do
    root to: 'home#index'
  end
  resources :shipping_companies, only: %i[index new create show] do
    member do
      patch 'deactivate'
      patch 'activate'
    end
  end
  resources :shipping_prices, only: %i[index new create]
  resources :min_shipping_prices, only: %i[new create]
  resources :shipping_deadlines, only: %i[index new create]
  resources :items, only: %i[new create]
  resources :quotes, only: %i[index] do
    get 'generated', on: :collection
  end
  resources :service_orders, only: %i[new create show index] do
    member do
      get 'set_vehicle'
      patch 'accept'
      patch 'reject'
    end
    resources :route_updates, only: %i[index create]
    get 'tracking', on: :collection
  end
  resources :vehicles, only: %i[index new create]
end

app/models/shipping_deadline.rb
class ShippingDeadline < ApplicationRecord
  belongs_to :shipping_company

  validates :start_distance, :end_distance, :deadline, presence: true
  validates :start_distance, :end_distance, numericality: { only_integer: true }
  validates :end_distance, comparison: { greater_than: :start_distance }, allow_blank: true, if: :start_distance
  validate :not_registered

  private

  def not_registered
    return unless shipping_company

    ranges = shipping_company.shipping_deadlines.pluck(:start_distance, :end_distance)
    message = 'já inclusa em intervalo cadastrado'
    errors.add(:start_distance, message) if ranges.detect { |s, e| (s...e).include?(start_distance) }
    return unless ranges.detect { |s, e| (s...e).include?(end_distance) }

    errors.add(:end_distance, message)
  end
end

app/controllers/shipping_deadlines_controller.rb
class ShippingDeadlinesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_shipping_company, only: %i[index create]

  def index
    @shipping_deadlines = @shipping_company.shipping_deadlines
  end

  def new
    @shipping_deadline = ShippingDeadline.new
  end

  def create
    @shipping_deadline = ShippingDeadline.new(params.require(:shipping_deadline).permit(:start_distance, :end_distance,
                                                                                        :deadline))
    @shipping_deadline.shipping_company = @shipping_company

    if @shipping_deadline.save
      flash[:success] = 'Prazo cadastrado com sucesso!'
      redirect_to shipping_deadlines_path
    else
      flash.now[:error] = 'Dados inválidos...'
      render 'new'
    end
  end

  private

  def set_shipping_company
    @shipping_company = current_user.shipping_company
  end
end

app/views/shipping_deadlines/_form.html.erb
<%= form_with model: @shipping_deadline do |f| %>
  <div>
    <%= f.label :start_distance %>
    <%= f.number_field :start_distance %>
  </div>
  <div>
    <%= f.label :end_distance %>
    <%= f.number_field :end_distance %>
  </div>
  <div>
    <%= f.label :deadline %>
    <%= f.number_field :deadline %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/shipping_deadlines/index.html.erb
<h2>Tabela de Prazos</h2>
<% if @shipping_deadlines.any? %>
  <table>
    <thead>
      <tr>
        <th>Distância (km)</th>
        <th>Dias úteis</th>
      </tr>
    </thead>
    <tbody>
      <% @shipping_deadlines.each do |shipping_deadline| %>
      <tr>
        <td><%= shipping_deadline.start_distance %>-<%= shipping_deadline.end_distance %>km</td>
        <td><%= shipping_deadline.deadline %> <%= t(:bussiness_day, count: shipping_deadline.deadline) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>Não existem prazos cadastrados</p>
<% end %>
<div>
  <%= link_to 'Novo Prazo', new_shipping_deadline_path %>
</div>

app/views/shipping_deadlines/new.html.erb
<h2>Cadastrar Prazo</h2>
<% if @shipping_deadline.errors.any? %>
  <p>Verifique os erros abaixo:</p>
  <ul>
    <% @shipping_deadline.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= render 'form' %>