config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins
  root to: 'home#index'
  namespace :user do
    root to: 'home#index'
  end
  namespace :admin do
    root to: 'home#index'
  end
  resources :shipping_companies, only: %i[index new create show] do
    member do
      patch 'deactivate'
      patch 'activate'
    end
  end
  resources :shipping_prices, only: %i[index new create]
  resources :min_shipping_prices, only: %i[new create]
  resources :shipping_deadlines, only: %i[index new create]
  resources :items, only: %i[new create]
  resources :quotes, only: %i[index] do
    get 'generated', on: :collection
  end
  resources :service_orders, only: %i[new create show index] do
    member do
      get 'set_vehicle'
      patch 'accept'
      patch 'reject'
    end
    resources :route_updates, only: %i[index create]
    get 'tracking', on: :collection
  end
  resources :vehicles, only: %i[index new create]
end

app/models/service_order.rb
class ServiceOrder < ApplicationRecord
  belongs_to :quote
  belongs_to :shipping_company
  belongs_to :vehicle, optional: true
  has_one :address, as: :addressable
  has_one :remittee
  has_many :route_updates
  accepts_nested_attributes_for :address, :remittee

  enum status: { pending: 5, accepted: 10, rejected: 15, in_transit: 20, finished: 25 }

  validates :quote_id, uniqueness: true

  before_create :generate_code

  def route_updates_attributes=(route_updates_attributes)
    route_updates_attributes.each do |i, attributes|
      route_updates.build(attributes)
    end
  end

  private

  def generate_code
    self.code = SecureRandom.alphanumeric(15).upcase
  end
end

app/controllers/service_orders_controller.rb
class ServiceOrdersController < ApplicationController
  devise_group :agent, contains: %i[user admin]
  before_action :authenticate_agent!, only: %i[index show]
  before_action :authenticate_admin!, only: %i[new create]
  before_action :authenticate_user!, only: %i[set_vehicle accept]
  before_action :set_service_order, only: %i[show set_vehicle accept reject]

  def new
    @quote = [Quote.find_by(code: params[:q])]
    @shipping_company = [@quote.first.shipping_company]
    @service_order = ServiceOrder.new
    @service_order.build_address
    remittee = @service_order.build_remittee
    remittee.build_address
  end

  def create
    @service_order = ServiceOrder.new(service_order_params)
    if @service_order.save
      flash[:success] = 'Ordem de Serviço criada com sucesso!'
      redirect_to @service_order
    else
      @quote = [@service_order.quote]
      @shipping_company = [@service_order.shipping_company]
      flash.now[:error] = 'Dados inválidos...'
      render 'new'
    end
  end

  def show
    if user_signed_in? && current_user.shipping_company != @service_order.shipping_company
      redirect_to root_path
    end
  end

  def index
    if admin_signed_in?
      @pending_service_orders = ServiceOrder.where(status: 'pending').order(created_at: :desc)
      @service_orders = ServiceOrder.where.not(status: 'pending').order(created_at: :desc)
    elsif user_signed_in?
      @pending_service_orders = ServiceOrder.where(status: 'pending', shipping_company: current_user.shipping_company)
                                            .order(created_at: :desc)
      @service_orders = ServiceOrder.where('shipping_company_id = ? AND NOT status = ?',
                                           current_user.shipping_company_id, 5).order(created_at: :desc)
    end
  end

  def set_vehicle
    redirect_to root_path if current_user.shipping_company != @service_order.shipping_company
    @vehicles = current_user.shipping_company.vehicles.order(:license_plate)
  end

  def accept
    service_order_params = params.require(:service_order).permit(:vehicle_id)
    if params[:service_order][:vehicle_id].present? && @service_order.update(service_order_params)
      @service_order.accepted!
      flash[:success] = 'Ordem de Serviço aceita!'
      redirect_to @service_order
    else
      flash.now[:error] = 'Dados inválidos...'
      render 'new'
    end
  end

  def reject
    @service_order.rejected!
    flash[:success] = 'Ordem de Serviço rejeitada!'
    redirect_to @service_order
  end

  def tracking
    return unless params[:tracking]

    @service_order = ServiceOrder.find_by(code: params[:tracking])
    return if @service_order

    flash.now[:error] = 'O código não foi encontrado...'
    render 'tracking'
  end

  private

  def service_order_params
    params
      .require(:service_order)
      .permit(:quote_id, :shipping_company_id,
              address_attributes: %i[street_name street_number complement district city state postal_code],
              remittee_attributes: [:id_number, :name, :surname,
                                    { address_attributes: %i[street_name street_number complement district city state
                                                             postal_code] }])
  end

  def set_service_order
    @service_order = ServiceOrder.find(params[:id])
  end
end

app/views/service_orders/index.html.erb
<h2>Ordens de Serviço</h2>
<% if @pending_service_orders.empty? && @service_orders.empty? %>
  <% if admin_signed_in? %>
    <p>Não existem ordens de serviço criadas</p>
  <% end %>
  <% if user_signed_in? %>
    <p>Nenhuma ordem de serviço</p>
  <% end %>
<% else %>
  <% if @pending_service_orders.any? %>
    <section id="pending-service-orders">
      <h3>Pendentes</h3>
      <%= render partial: 'shared/service_orders/service_orders', locals: { service_orders: @pending_service_orders } %>
    </section>
  <% end %>
  <% if @service_orders.any? %>
    <section id="processed-service-orders">
      <h3>Processadas</h3>
      <%= render partial: 'shared/service_orders/service_orders', locals: { service_orders: @service_orders } %>
    </section>
  <% end %>
<% end %>

app/views/service_orders/new.html.erb
<h2>Nova Ordem de Serviço</h2>
<% if @service_order.errors.any? %>
  <p>Verifique os erros abaixo:</p>
  <ul>
    <% @service_order.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_for @service_order do |f| %>
  <div>
    <%= f.label :quote_id %>
    <%= f.collection_select :quote_id, @quote, :id, :code %>
  </div>
  <div>
    <%= f.label :shipping_company_id %>
    <%= f.collection_select :shipping_company_id, @shipping_company, :id, :full_description %>
  </div>
  <div id="remitter">
    <h3>Endereço para retirada</h3>
    <%= f.fields_for :address do |address_f| %>
      <%= render partial: 'shared/address/form', locals: { f: address_f } %>
    <% end %>
  </div>
  <div id="remittee">
    <h3>Informações para entrega</h3>
    <h4>Destinatário</h4>
    <%= f.fields_for :remittee do |remittee_f| %>
      <div>
        <%= remittee_f.label :id_number %>
        <%= remittee_f.number_field :id_number %>
      </div>
      <div>
        <%= remittee_f.label :name %>
        <%= remittee_f.text_field :name %>
      </div>
      <div>
        <%= remittee_f.label :surname %>
        <%= remittee_f.text_field :surname %>
      </div>
      <h4>Endereço</h4>
      <div>
        <%= remittee_f.fields_for :address do |remittee_address_f| %>
          <%= render partial: 'shared/address/form', locals: { f: remittee_address_f } %>
        <% end %>
      </div>
    <% end %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/service_orders/set_vehicle.html.erb
<h2>Aceitar Ordem de Serviço</h2>
<%= form_with model: @service_order, url: accept_service_order_path, method: 'patch' do |f|  %>
  <div>
    <%= f.label :vehicle_id %>
    <%= f.collection_select :vehicle_id, @vehicles, :id, :full_description, required: true %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/service_orders/show.html.erb
<h2>Ordem de Serviço <%= @service_order.code %></h2>
<% unless @service_order.accepted? %>
  <span>[<%= t(@service_order.status) %>]</span>
<% end %>
<div>
  <dl>
    <dt><strong>Data:</strong></dt>
    <dd><%= l(@service_order.created_at.to_date) %></dd>
    <% if admin_signed_in? %>
      <dt><strong>Transportadora:</strong></dt>
      <dd><%= @service_order.shipping_company.full_description %></dd>
    <% end %>
    <div id="item">
      <h3>Item <%= @service_order.quote.item.sku %></h3>
      <dt><strong>Dimensões:</strong></dt>
      <dd><%= @service_order.quote.item.full_dimensions %></dd>
      <dt><strong>Peso:</strong></dt>
      <dd><%= @service_order.quote.item.weight.fdiv(1000).to_i %>kg</dd>
    </div>
    <dt><strong>Endereço para retirada:</strong></dt>
    <dd><%= @service_order.address.full_address %></dd>
    <div id="remittee">
      <h3>Destinatário</h3>
      <dt><strong>Doc. de Identificação:</strong></dt>
      <dd><%= @service_order.remittee.id_number %></dd>
      <dt><strong>Nome Completo:</strong></dt>
      <dd><%= @service_order.remittee.full_name %></dd>
    </div>
    <dt><strong>Endereço para entrega:</strong></dt>
    <dd><%= @service_order.remittee.address.full_address %></dd>
    <dt><strong>Valor do frete:</strong></dt>
    <dd><%= number_to_currency(@service_order.quote.price) %></dd>
    <dt><strong>Estimativa de entrega:</strong></dt>
    <dd><%= @service_order.quote.deadline %> <%= t(:bussiness_day, count: @service_order.quote.deadline) %></dd>
    <% if @service_order.accepted? %>
      <dt><strong>Veículo responsável pela entrega:</strong></dt>
      <dd><%= @service_order.vehicle.full_description %></dd>
    <% end %>
  </dl>
</div>
<% if user_signed_in? %>
  <div>
    <% if @service_order.pending? %>
      <%= link_to 'Aceitar Ordem de Serviço', set_vehicle_service_order_path(@service_order) %>
      <%= button_to 'Rejeitar Ordem de Serviço', reject_service_order_path(@service_order), method: :patch %>
    <% elsif @service_order.accepted? %>
      <%= link_to 'Atualizações de Rota', service_order_route_updates_path(@service_order) %>
    <% end %>
  </div>
<% end %>
<div>
  <%= link_to 'Voltar', service_orders_path %>
</div>

app/views/service_orders/tracking.html.erb
<h2>Rastreamento</h2>
<div>
  <%= form_with url: tracking_service_orders_path, method: :get do |f| %>
    <div>
      <%= f.label :tracking, 'Código de rastreamento' %>
      <%= f.text_field :tracking %>
    </div>
    <div>
      <%= f.submit 'Rastrear' %>
    </div>
  <% end %>
</div>
<% if @service_order %>
  <div>
    <h3>Ordem de Serviço: <%= @service_order.code %></h3>
    <dl>
      <dt><strong>Origem:</strong></dt>
      <dd><%= @service_order.address.full_address %></dd>
      <dt><strong>Destino:</strong></dt>
      <dd><%= @service_order.remittee.address.full_address %></dd>
      <dt><strong>Transportado por:</strong></dt>
      <dd><%= @service_order.vehicle.full_description %></dd>
    </dl>
    <%= render 'shared/service_orders/route_updates' %>
  </div>
<% end %>