config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins
  root to: 'home#index'
  namespace :user do
    root to: 'home#index'
  end
  namespace :admin do
    root to: 'home#index'
  end
  resources :shipping_companies, only: %i[index new create show] do
    member do
      patch 'deactivate'
      patch 'activate'
    end
  end
  resources :shipping_prices, only: %i[index new create]
  resources :min_shipping_prices, only: %i[new create]
  resources :shipping_deadlines, only: %i[index new create]
  resources :items, only: %i[new create]
  resources :quotes, only: %i[index] do
    get 'generated', on: :collection
  end
  resources :service_orders, only: %i[new create show index] do
    member do
      get 'set_vehicle'
      patch 'accept'
      patch 'reject'
    end
    resources :route_updates, only: %i[index create]
    get 'tracking', on: :collection
  end
  resources :vehicles, only: %i[index new create]
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :shipping_company
  has_many :service_orders

  validates :license_plate, :make, :model, :year, :max_load, presence: true

  def full_description
    "#{license_plate} - #{make} #{model}"
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  def index
    @vehicles = current_user.shipping_company.vehicles
  end

  def new
    @vehicle = Vehicle.new
  end

  def create
    @vehicle = Vehicle.new(params.require(:vehicle).permit(:license_plate, :make, :model, :year, :max_load))
    @vehicle.shipping_company = current_user.shipping_company
    if @vehicle.save
      flash[:success] = 'Veículo cadastrado com sucesso!'
      redirect_to vehicles_path
    else
      flash.now[:error] = 'Dados inválidos...'
      render 'new'
    end
  end
end

app/views/vehicles/_form.html.erb
<%= form_with model: @vehicle do |f| %>
  <div>
    <%= f.label :license_plate %>
    <%= f.text_field :license_plate %>
  </div>
  <div>
    <%= f.label :make %>
    <%= f.text_field :make %>
  </div>
  <div>
    <%= f.label :model %>
    <%= f.text_field :model %>
  </div>
  <div>
    <%= f.label :year %>
    <%= f.number_field :year %>
  </div>
  <div>
    <%= f.label :max_load %>
    <%= f.text_field :max_load %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/vehicles/index.html.erb
<h2>Veículos</h2>
<% if @vehicles.any? %>
  <table>
    <thead>
      <tr>
        <th>Placa</th>
        <th>Marca</th>
        <th>Modelo</th>
        <th>Ano de Fabricação</th>
        <th>Capacidade Máxima (kg)</th>
      </tr>
    </thead>
    <tbody>
      <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.license_plate %></td>
        <td><%= vehicle.make %></td>
        <td><%= vehicle.model %></td>
        <td><%= vehicle.year %></td>
        <td><%= vehicle.max_load %>kg</td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>Não existem veículos cadastrados</p>
<% end %>
<div>
  <%= link_to 'Novo Veículo', new_vehicle_path %>
</div>

app/views/vehicles/new.html.erb
<h2>Cadastrar Veículo</h2>
<% if @vehicle.errors.any? %>
  <p>Verifique os erros abaixo:</p>
  <ul>
    <% @vehicle.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= render 'form' %>